language: cpp
sudo: required
service:
- docker
env:
  global:
  - MY_NAME=travis-ci
  - MY_TARGET_DIST=ubuntu:18.04
  - MY_TARGET_MOUNT=/tell/sodium-drbg
matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    env:
    - MY_MODE="cpp"
    - MY_CPATH=cybozulib/include
  - os: linux
    dist: xenial
    language: python
    env:
    - MY_MODE="python"
before_install:
- ./travis-ci/before_install_$TRAVIS_OS_NAME.bash
install:
- ./travis-ci/install_$TRAVIS_OS_NAME.bash
before_script:
- env
- docker exec -ti $MY_NAME bash -c "env"
- ./travis-ci/before_script_$TRAVIS_OS_NAME.bash
script:
- ./travis-ci/script_$TRAVIS_OS_NAME.bash
# after_failure:
# - tail -n 1000 make.log
notifications:
  on_success: change
  on_failure: always
# vim: set expandtab shiftwidth=2 softtabstop=2 :
